package org.qudus.squad
fun main ( ) {
    println("ΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞ   PLAN MATE  ΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞ")
    println("┌───────────────────────────────────────────┐")
    println("│               WELCOME USERNAME            │")
    println("│───────────────────────────────────────────│")
    println("│              1- ALL PROJECTS              │")
    println("│              3- RECENT LOGS               │")
    println("│              0- LOG OUT                   │")
    println("└───────────────────────────────────────────┘")

    println("ΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞ   PLAN MATE  ΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞ")
    println("┌─────────────────────────────────────────────────┐")
    println("│                   FIND PROJECT                  │")
    println("│─────────────────────────────────────────────────│")
    println("│      ID      │        NAME     │  DATE CREATED  │")
    println("│  PROJECT_ID  │    PROJECT_NAME │   PROJECT_LOG  │")
    println("│  PROJECT_ID  │    PROJECT_NAME │   PROJECT_LOG  │")
    println("│  PROJECT_ID  │    PROJECT_NAME │   PROJECT_LOG  │")
    println("└─────────────────────────────────────────────────┘")
    println("┌─────────────────────────────────────────────────┐")
    println("│     ENTER PROJECT NAME OR ID TO OPEN PROJECT    │")
    println("└─────────────────────────────────────────────────┘")

    println("ΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞ   PLAN MATE  ΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞΞ")
    println("┌─────────────────────────────────────────────────┐")
    println("│                   GAME PROJECT                  │")
    println("│                   $ DESCRIPTION                 │")
    println("│─────────────────────────────────────────────────│")
    println("│      STATE1     │    STATE2     │     STATE3    │")
    println("│─────────────────────────────────────────────────│")
    println("│      ▫TASK1     │    ▫TASK2     │     ▫TASK3    │")
    println("│      ▫TASK4     │    ▫TASK5     │     ▫TASK6    │")
    println("│                 │               │     ▫TASK7    │")
    println("└─────────────────────────────────────────────────┘")

    println("┌─────────────────────────────────────────┐")
    println("│               MANAGE TASKS              │")
    println("│─────────────────────────────────────────│")
    println("│1- CREATE NEW TASK  │ 4- DELETE TASK     │")
    println("│2- EDIT TASK NAME   │ 5- ASSIGN TO TASK  │")
    println("│3- EDIT TASK        │ 6- SWITCH TASK     │")
    println("│    DESCRIPTION     │  TO ANOTHER STATE  │")
    println("│                0- RETURN                │")
    println("└─────────────────────────────────────────┘")
}
